### ISSUE TITLE
Crash when resizing window

### ISSUE THREAD

**Issue by bioglaze** [chaoticbob/tinyrenderers#7]
When running on Ubuntu 17.10, Radeon R9 Nano with the latest drivers (oibaf PPA), samples crash when resizing the window (eg. 03_UniformBuffer_VK):

```
#3  0x00007ffff5d64fc2 in __GI___assert_fail (assertion=0x5555555ad780 "VK_SUCCESS == vk_res", file=0x5555555acbe8 "/home/glaze/Downloads/tinyrenderers/tinyvk.h", line=5459, 
    function=0x5555555b1d20 <tr_internal_vk_acquire_next_image(tr_renderer*, tr_semaphore*, tr_fence*)::__PRETTY_FUNCTION__> "void tr_internal_vk_acquire_next_image(tr_renderer*, tr_semaphore*, tr_fence*)") at assert.c:101
#4  0x0000555555576d05 in tr_internal_vk_acquire_next_image(tr_renderer*, tr_semaphore*, tr_fence*) ()
#5  0x000055555556b10d in tr_acquire_next_image ()
#6  0x000055555559251f in draw_frame() ()
#7  0x0000555555592a46 in main ()

```

**Comment by chaoticbob** [comment]
Oh yeah, I didn't think about this too hard when working on it initially. Sorry. I'll fix it when I have some time soon.
